# Generated by Django 4.1.8 on 2025-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_especialidad_hospital_medico_user_paciente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='estatura',
            field=models.CharField(blank=True, help_text='Estatura en metros (ej. 1.75)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, help_text='Frecuencia cardiaca en bpm', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='peso',
            field=models.CharField(blank=True, help_text='Peso en kg (ej. 72.5)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='presion_arterial',
            field=models.CharField(blank=True, help_text='Ejemplo: 120/80 mmHg', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='temperatura',
            field=models.CharField(blank=True, help_text='Temperatura en °C (ej. 36.8)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recetamedicamento',
            name='dosis',
            field=models.CharField(help_text='Ejemplo: 1 tableta cada 8 horas por 7 días', max_length=1055),
        ),
        migrations.AlterField(
            model_name='recetamedicamento',
            name='medicamento',
            field=models.CharField(help_text='Nombre del medicamento (ej. Amoxicilina 500mg)', max_length=1055),
        ),
    ]
