# Generated by Django 4.1.8 on 2025-08-12 17:32

from django.db import migrations

def crear_especialidades(apps, schema_editor):
    Especialidad = apps.get_model('core', 'Especialidad')
    especialidades = [
        'Medico',
        'Odontologo',
        'Psicologo',
        'Nutricionista',
    ]
    for nombre in especialidades:
        Especialidad.objects.get_or_create(nombre=nombre)

def eliminar_especialidades(apps, schema_editor):
    Especialidad = apps.get_model('core', 'Especialidad')
    Especialidad.objects.filter(
        nombre__in=['Medico', 'Odontologo', 'Psicologo', 'Nutricionista']
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_ciudad_alter_paciente_dni'),
    ]

    operations = [
        migrations.RunPython(crear_especialidades, eliminar_especialidades),
    ]
