# Generated by Django 4.1.8 on 2025-08-12 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_default_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='tipo_licencia',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('pagada', 'Pagada')], default='prueba', max_length=10),
        ),
    ]
