# Generated by Django 4.1.8 on 2025-08-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medico_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_asignados', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_asignados', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Asignación Médico-Paciente',
                'verbose_name_plural': 'Asignaciones Médico-Paciente',
                'unique_together': {('paciente', 'medico')},
            },
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Medico_Paciente',
        ),
    ]
