# Generated by Django 4.1.8 on 2025-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicopaciente_alter_cita_estado_alter_cita_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='odontograma',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
