# Generated by Django 4.1.8 on 2025-09-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_odontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='core.cita'),
            preserve_default=False,
        ),
    ]
