# Generated by Django 4.1.8 on 2025-10-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
