"""
Django settings for galeno project.

Generated by 'django-admin startproject' using Django 4.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ajhx_=(p2-kwj3l^ot25^1d@8pxprw_%49jr4d&o1fm@ubv=!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_recaptcha',
    # Galeno
    'core',

    # 3rd party
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'galeno.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'galeno.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
	'ENGINE': 'django.db.backends.postgresql',
	'NAME': 'galeno',
	'USER': 'hector',
	'PASSWORD': 'suazo000000',
	'HOST': '',
	'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'

STATIC_URL = '/static/'
STATIC_ROOT = '/home/hector/apps/galeno-static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# reCAPTCHA v3
RECAPTCHA_PUBLIC_KEY = '6LfJK2wrAAAAAPGkkwXsfeW3WYQUwQaDJpiflOvY'
RECAPTCHA_PRIVATE_KEY = '6LfJK2wrAAAAABsl1Ze-F9vfN3LTzra7GkGs_W33'
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5  # Puedes ajustarlo

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Cambia a smtp.de.opalstack.com si tu servidor está en Alemania
EMAIL_HOST = 'smtp.us.opalstack.com'

EMAIL_PORT = 587              # TLS recomendado
EMAIL_USE_TLS = True          # o EMAIL_USE_SSL = True si usas el puerto 465
EMAIL_USE_SSL = False         # asegúrate de que sea falso si usas TLS (587)

EMAIL_HOST_USER = 'galeno'  # 👈 SOLO el nombre del buzón, no el correo
# Tus credenciales de Opalstack
# EMAIL_HOST_USER = 'info@galenosoft.com'        # Tu correo completo
EMAIL_HOST_PASSWORD = '0AS3YxIOlI0LXJl'        # Contraseña del buzón

DEFAULT_FROM_EMAIL = 'info@galenosoft.com'


MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # útil para usar con Bootstrap
}


#Import Settings
try:
    from myproject.local_settings import *
except ImportError:
    pass
